/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppCreditsRouteImport } from './routes/app.credits'
import { Route as AppHistoriqueRouteImport } from './routes/app.historique'
import { Route as AppParametresRouteImport } from './routes/app.parametres'
import { Route as AppProduitsRouteImport } from './routes/app.produits'
import { Route as AppStockRouteImport } from './routes/app.stock'
import { Route as AppVentesRouteImport } from './routes/app.ventes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/app/clients',
  path: '/app/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCreditsRoute = AppCreditsRouteImport.update({
  id: '/app/credits',
  path: '/app/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHistoriqueRoute = AppHistoriqueRouteImport.update({
  id: '/app/historique',
  path: '/app/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParametresRoute = AppParametresRouteImport.update({
  id: '/app/parametres',
  path: '/app/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProduitsRoute = AppProduitsRouteImport.update({
  id: '/app/produits',
  path: '/app/produits',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStockRoute = AppStockRouteImport.update({
  id: '/app/stock',
  path: '/app/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVentesRoute = AppVentesRouteImport.update({
  id: '/app/ventes',
  path: '/app/ventes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/tarifs': typeof TarifsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/historique': typeof AppHistoriqueRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/tarifs': typeof TarifsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/historique': typeof AppHistoriqueRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connexion': typeof ConnexionRoute
  '/faq': typeof FaqRoute
  '/inscription': typeof InscriptionRoute
  '/onboarding': typeof OnboardingRoute
  '/tarifs': typeof TarifsRoute
  '/app/clients': typeof AppClientsRoute
  '/app/credits': typeof AppCreditsRoute
  '/app/historique': typeof AppHistoriqueRoute
  '/app/parametres': typeof AppParametresRoute
  '/app/produits': typeof AppProduitsRoute
  '/app/stock': typeof AppStockRoute
  '/app/ventes': typeof AppVentesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connexion'
    | '/faq'
    | '/inscription'
    | '/onboarding'
    | '/tarifs'
    | '/app/clients'
    | '/app/credits'
    | '/app/historique'
    | '/app/parametres'
    | '/app/produits'
    | '/app/stock'
    | '/app/ventes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connexion'
    | '/faq'
    | '/inscription'
    | '/onboarding'
    | '/tarifs'
    | '/app/clients'
    | '/app/credits'
    | '/app/historique'
    | '/app/parametres'
    | '/app/produits'
    | '/app/stock'
    | '/app/ventes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/connexion'
    | '/faq'
    | '/inscription'
    | '/onboarding'
    | '/tarifs'
    | '/app/clients'
    | '/app/credits'
    | '/app/historique'
    | '/app/parametres'
    | '/app/produits'
    | '/app/stock'
    | '/app/ventes'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnexionRoute: typeof ConnexionRoute
  FaqRoute: typeof FaqRoute
  InscriptionRoute: typeof InscriptionRoute
  OnboardingRoute: typeof OnboardingRoute
  TarifsRoute: typeof TarifsRoute
  AppClientsRoute: typeof AppClientsRoute
  AppCreditsRoute: typeof AppCreditsRoute
  AppHistoriqueRoute: typeof AppHistoriqueRoute
  AppParametresRoute: typeof AppParametresRoute
  AppProduitsRoute: typeof AppProduitsRoute
  AppStockRoute: typeof AppStockRoute
  AppVentesRoute: typeof AppVentesRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/app/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/credits': {
      id: '/app/credits'
      path: '/app/credits'
      fullPath: '/app/credits'
      preLoaderRoute: typeof AppCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/historique': {
      id: '/app/historique'
      path: '/app/historique'
      fullPath: '/app/historique'
      preLoaderRoute: typeof AppHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parametres': {
      id: '/app/parametres'
      path: '/app/parametres'
      fullPath: '/app/parametres'
      preLoaderRoute: typeof AppParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/produits': {
      id: '/app/produits'
      path: '/app/produits'
      fullPath: '/app/produits'
      preLoaderRoute: typeof AppProduitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stock': {
      id: '/app/stock'
      path: '/app/stock'
      fullPath: '/app/stock'
      preLoaderRoute: typeof AppStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/ventes': {
      id: '/app/ventes'
      path: '/app/ventes'
      fullPath: '/app/ventes'
      preLoaderRoute: typeof AppVentesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnexionRoute: ConnexionRoute,
  FaqRoute: FaqRoute,
  InscriptionRoute: InscriptionRoute,
  OnboardingRoute: OnboardingRoute,
  TarifsRoute: TarifsRoute,
  AppClientsRoute: AppClientsRoute,
  AppCreditsRoute: AppCreditsRoute,
  AppHistoriqueRoute: AppHistoriqueRoute,
  AppParametresRoute: AppParametresRoute,
  AppProduitsRoute: AppProduitsRoute,
  AppStockRoute: AppStockRoute,
  AppVentesRoute: AppVentesRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
