import { Link } from "@tanstack/react-router";
import { Menu, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Brand } from "./brand";
import { Button } from "@/components/ui/button";
export function PublicHeader(){const[open,setOpen]=useState(false);return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="container-shell grid h-18 grid-cols-[minmax(0,1fr)_auto] items-center"><Brand/><nav className="hidden items-center gap-8 lg:flex">{[["Fonctionnalités","/#fonctionnalites"],["Solutions","/#solutions"],["Tarifs","/tarifs"],["FAQ","/faq"]].map(([label,to])=><a key={label} href={to} className="text-sm font-medium text-muted-foreground transition hover:text-foreground">{label}</a>)}</nav><div className="hidden items-center gap-2 lg:flex"><Button variant="ghost" asChild><Link to="/connexion">Se connecter</Link></Button><Button asChild><Link to="/inscription">Commencer gratuitement</Link></Button></div><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label="Ouvrir le menu">{open?<X/>:<Menu/>}</Button></div>{open&&<div className="border-t border-border bg-background px-5 py-5 lg:hidden"><nav className="grid gap-1">{[["Fonctionnalités","/#fonctionnalites"],["Solutions","/#solutions"],["Tarifs","/tarifs"],["FAQ","/faq"],["Se connecter","/connexion"],["Commencer gratuitement","/inscription"]].map(([label,to])=><a key={label} href={to} onClick={()=>setOpen(false)} className="rounded-md px-3 py-3 text-sm font-semibold hover:bg-muted">{label}</a>)}</nav></div>}</header>}
const footerColumns = [
  { title: "Produit", links: [["Fonctionnalités", "/#fonctionnalites"], ["Solutions", "/#solutions"], ["Tarifs", "/tarifs"], ["FAQ", "/faq"]] },
  { title: "Confiance", links: [["Sécurité", "/#securite"], ["Confidentialité", "/#securite"], ["Mentions légales", "/#securite"]] },
  { title: "Entreprise", links: [["Contact", "mailto:contact@bitik.tech"], ["Se connecter", "/connexion"], ["Créer un compte", "/inscription"]] },
];
export function PublicFooter(){return <footer className="border-t border-border bg-ink py-14 text-ink-foreground"><div className="container-shell grid gap-10 md:grid-cols-[1.3fr_repeat(3,1fr)]"><div><Brand inverse/><p className="mt-5 max-w-xs text-sm leading-6 text-ink-muted">La plateforme de gestion pensée pour les boutiques de téléphonie et d’électronique.</p></div>{footerColumns.map(({title,links})=><div key={title}><b className="text-sm">{title}</b><ul className="mt-4 space-y-3 text-sm text-ink-muted">{links.map(([label,href])=><li key={label}><a className="transition hover:text-ink-foreground" href={href}>{label}</a></li>)}</ul></div>)}</div><div className="container-shell mt-12 border-t border-ink-border pt-6 text-xs text-ink-muted">© 2026 Bitik Tech. Tous droits réservés.</div></footer>}
export function PublicLayout({children}:{children:ReactNode}){return <><PublicHeader/><main>{children}</main><PublicFooter/></>}
